//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net47_forms_crud_001.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bd_estacionamientosEntities1 : DbContext
    {
        public bd_estacionamientosEntities1()
            : base("name=bd_estacionamientosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autos_cliente> autos_cliente { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<estado_plaza> estado_plaza { get; set; }
        public virtual DbSet<plaza_autos> plaza_autos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<sp_lista_clientes_Result> sp_lista_clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_clientes_Result>("sp_lista_clientes");
        }
    }
}
